language: ruby
rvm:
  - 2.2.0

services:
  - mongodb

bundler_args: "--without development"
install:
  - pushd .
  - bash .travis.d/install.sh
  - popd
before_script:
  - pushd .
  - bash .travis.d/before_script.sh
  - popd
script: allow_open_jtalk=1 bundle exec rspec
