production: &production
  # smtp or sendmail
  delivery_method: sendmail

  # smtp settings
  address: localhost
  port: 25
  domain: localhost
  user_name:
  password:
  authentication:

  # sendmail settings
  location:
  arguments:

  # message settings
  default_from:
  default_charset: iso-2022-jp

test:
  <<: *production

development:
  <<: *production
